# Configurations
title:            Stable Diffusion webUI
longtitle:        Stable Diffusion webUI
email:            ''
description: >
  A browser interface based on Gradio library for Stable Diffusion.

version:          1.0
gitbook_version:  3.2.3

url:              'https://github.com/ProfaneServitor/sdwui-docs'
baseurl:          '/sdwui-docs'
rss:              RSS

# bootstrap: use the remote theme for the site itself
# remote_theme: sighingnow/jekyll-gitbook
remote_theme: NrdyBhu1/atlas-jekyll-theme 

toc:
  enabled: true
  h_min: 1
  h_max: 5

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext
# permalink: pretty

exclude:
  - _drafts
  - [vendor]

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
  - jekyll-polyglot
  - jekyll-timeago
  - jekyll-relative-links
  - jekyll-toc

languages: ["en", "ru", "de"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

relative_links:
  enabled:     true
  collections: false

Guides:
  en: Guides
  ru: Руководства
